### ISSUE TITLE
Support for xml:id?

### ISSUE THREAD

**Issue by buko** [etourdot/xincproc#7]
Does this engine support the [xml:id Spec](https://www.w3.org/TR/xml-id/)?

What we'd like to do is described in [this StackOverflow Question](https://stackoverflow.com/questions/50294372/trying-to-use-xinclude-with-java-and-resolving-the-fragment-with-xmlid): The basic idea is include fragments from another document which does not define a DTD but rather uses the xml:id specification.

**Comment by etourdot** [comment]
Yes, xincprox is following the xinclude 1.0 specification according to this confomance: http://etourdot.github.io/xincproc/xinclude/specs/org/etourdot/xincproc/xinclude/testsuite/Testsuite.html

with base document:
```
<doc xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="input-en.xml" xpointer="element(para-en)"/>
</doc>
```
and a target document "input-en.xml":
```
<doc xml:lang="en">
<title>A Document</title>
<para xml:id="para-en">This paragraph is in English.</para>
</doc>
```
the result of the transformation will be
```
<doc>
 <para xml:id="para-en" xml:lang="en">This paragraph is in English.</para>
</doc>
```

**Comment by buko** [comment]
Thanks for the quick response.
